/**
 * \file fr9009_config.c
 * \brief Contains FR9009 configuration settings for the FR9009 API
 *
 * Copyright 2022 BriRadio.
 * Released under the FR9009 API license, for more information see the "LICENSE.txt" file in this zip file.
 *
 * The top level structure fr9009Device_t talDevice uses keyword
 * extern to allow the application layer main() to have visibility
 * to these settings.
 *
 * This file may not be fully complete for the end user application and 
 * may need to updated for AGC, GPIO, and DAC full scale settings. 
 * To create a full initialisation routine, the user should also refer to the 
 * Iron Python initialisation routine generated by the GUI, and also the FR9009 User Guide.
 *
 */
#include "fr9009_types.h"
#include "fr9009_config.h"
#include "fr9009_error.h"
#include "fr9009_agc.h"

// Fpass = 0.5, Fstop = 0.6, Apass = 0.1, Astop = 60
int16_t cfirCoefs_0p5[56] = {54, 80, -35, -70, 68, 84, -126, -78, 197, 49, -283, 22, 372, -145, -448, 333, 489, -597, -463, 956, 323, -1446, 22, 2189, -838, -3733, 3759, 15742, 15742, 3759, -3733, -838, 2189, 22, -1446, 323, 956, -463, -597, 489, 333, -448, -145, 372, 22, -283, 49, 197, -78, -126, 84, 68, -70, -35, 80, 54};

// Fpass = 0.25, Fstop = 0.3, Apass = 0.1, Astop = 60
int16_t cfirCoefs_0p25[111] = {33, 36, 33, 11, -21, -44, -42, -11, 30, 53, 37, -14, -67, -83, -44, 32, 95, 94, 21, -83, -145, -111, 7, 137, 183, 98, -75, -221, -227, -68, 163, 307, 242, -13, -301, -411, -234, 144, 475, 506, 160, -371, -725, -600, 9, 750, 1092, 669, -420, -1556, -1869, -720, 1877, 5150, 7870, 8924, 7870, 5150, 1877, -720, -1869, -1556, -420, 669, 1092, 750, 9, -600, -725, -371, 160, 506, 475, 144, -234, -411, -301, -13, 242, 307, 163, -68, -227, -221, -75, 98, 183, 137, 7, -111, -145, -83, 21, 94, 95, 32, -44, -83, -67, -14, 37, 53, 30, -11, -42, -44, -21, 11, 33, 36, 33};

#define TX_FLATNESSCOEFS_LEN 32
#if REFCLK_FREQ_KHZ * TX_INRATE_IS_REF_MULT >= 400000 
int16_t txFlatnessFlt_II[TX_FLATNESSCOEFS_LEN] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, -156, 466, -2181, 20148, -2181, 466, -156, 64, };// TX 400M
#elif REFCLK_FREQ_KHZ * TX_INRATE_IS_REF_MULT >= 200000 
int16_t txFlatnessFlt_II[TX_FLATNESSCOEFS_LEN] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, -39, 117, -545, 17399, -545, 117, -39, 16, };// TX 200M
#else
int16_t txFlatnessFlt_II[TX_FLATNESSCOEFS_LEN] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16384, 0, 0, 0, 0, };// TX < 200M
#endif
int16_t txFlatnessFlt_QI[TX_FLATNESSCOEFS_LEN] = {0};
int16_t txFlatnessFlt_IQ[TX_FLATNESSCOEFS_LEN] = {0};

#define RX_FLATNESSCOEFS_LEN 32
#if REFCLK_FREQ_KHZ * RX_OUTRATE_IS_REF_MULT >= 400000 
int16_t rxFlatnessFlt_II[RX_FLATNESSCOEFS_LEN] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1030, -4882, 24303, -4882, 1030, }; // RX/ORX 400M
#elif REFCLK_FREQ_KHZ * RX_OUTRATE_IS_REF_MULT >= 200000 
int16_t rxFlatnessFlt_II[RX_FLATNESSCOEFS_LEN] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 433, -1226, 18389, -1226, 433, };// RX/ORX 200M
#else
int16_t rxFlatnessFlt_II[RX_FLATNESSCOEFS_LEN] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16384, 0, 0, 0, 0, };// RX/ORX <200M
#endif
int16_t rxFlatnessFlt_QI[RX_FLATNESSCOEFS_LEN] = {0};
int16_t rxFlatnessFlt_IQ[RX_FLATNESSCOEFS_LEN] = {0};

#define PRE_CALI_FREQ_LEN   10
uint32_t rfpreCaliFreqs_khz[PRE_CALI_FREQ_LEN] ={300000, 800000, 1000000, 1500000, 2000000, 2500000, 3500000, 4000000, 4500000, 500000};
#define FHM_RF_LEN  10
int32_t FhmRfFreqs_khz[FHM_RF_LEN]={435000, 650000, 900000, 1450000, 1800000, 2600000,  3200000, 4150000,  5300000, 5200000};
#define FHM_ORF_LEN  10
int32_t FhmORfFreqs_khz[FHM_ORF_LEN]={380000, 800000, 1280000, 1600000, 1950000, 2900000,  3500000, 5100000,  4050000, 1300000};

#define FHM_RX_NCO_LEN  10
int32_t rxNcoFreqs[FHM_RX_NCO_LEN]={10000000, -10000000, 20000000, -20000000, 30000000, -30000000,  40000000, -40000000,  50000000, -50000000};
#define FHM_TX_NCO_LEN  20
int32_t txNcoFreqs[FHM_TX_NCO_LEN]={1000, -1000, 2000, -2000, 3000, -3000,  4000, -4000,  5000, -5000};

fr9009Init_t talInit =
{
	/* SPI settings */
    .spiSettings =
    {
		.MSBFirst            = 1,  /* 1 = MSBFirst, 0 = LSBFirst */
		.enSpiStreaming      = 0,  /* Not implemented in ADIs platform layer. SW feature to improve SPI throughput */
		.autoIncAddrUp       = 1,  /* Not implemented in ADIs platform layer. For SPI Streaming, set address increment direction. 1= next addr = addr+1, 0:addr=addr-1 */
		.fourWireMode        = 1,  /* 1: Use 4-wire SPI, 0: 3-wire SPI (SDIO pin is bidirectional). NOTE: ADI's FPGA platform always uses 4-wire mode */
		.cmosPadDrvStrength  = FR_CMOSPAD_DRV_2X /* Drive strength of CMOS pads when used as outputs (SDIO, SDO, GP_INTERRUPT, GPIO 1, GPIO 0) */
	},
	
    /* Rx settings */
    .rx = 
    {
        .rxProfile =
        {
            .rxOutputRate_kHz = REFCLK_FREQ_KHZ * RX_OUTRATE_IS_REF_MULT,            /* Rx IQ data rate in kHz */            
            .rxFir = 
            {
            	.symmetric = 0,
				.even = 0,
                .gain_dB = FR_FIR_GAIN_0_DB,                 /* filter gain */
                .numFirCoefs = 0,                   		/* number of coefficients in the FIR filter */
                .coefs = NULL, 
            },
            .rxIfConvMode = {FR_IFCONV_BYPASS, FR_IFCONV_BYPASS},  /* Rx DDC mode */
            .rxIfConvCfg = {
                {
                .bandAFe = {0},
                .bandABe = {0},
                .bandBFe = {0},
                .bandBBe = {0},
                .bandSel = 0
                },{
                .bandAFe = {0},
                .bandABe = {0},
                .bandBFe = {0},
                .bandBBe = {0},
                .bandSel = 0
                },
            },
            .rxMixer = {.freq_Hz = LIF_NCO_FREQ_HZ},
            .rxAdcMode = FR_ADC_IQ2ITLV,
            .rfDirectModeEn={0,0},
            .rxFlatnessFir = {
                {
                    .numFirCoefs = RX_FLATNESSCOEFS_LEN,
                    .coefs_II = &rxFlatnessFlt_II[0],
                    .coefs_QQ = &rxFlatnessFlt_II[0],
                    .coefs_IQ = &rxFlatnessFlt_IQ[0],
                    .coefs_QI = &rxFlatnessFlt_QI[0],
                },{
                    .numFirCoefs = RX_FLATNESSCOEFS_LEN,
                    .coefs_II = &rxFlatnessFlt_II[0],
                    .coefs_QQ = &rxFlatnessFlt_II[0],
                    .coefs_IQ = &rxFlatnessFlt_IQ[0],
                    .coefs_QI = &rxFlatnessFlt_QI[0],
                }
            },
        },
        .framerSel = FR_FRAMER_A,            /* Rx JESD204b framer configuration */
        .rxGainCtrl = 
        {
            .gainMode = FR_MGC,            /* fr9009rxGainMode_t gainMode */
            .FeAttCaliEn = 0,               /*Fe attention calibrate enable, use dig gain to fix*/
            .rx1GainIndex = 63,            /* uint8_t rx1GainIndex */
            .rx2GainIndex = 195,            /* uint8_t rx2GainIndex */
            .rx1MaxGainIndex = 63,            /* uint8_t rx1MaxGainIndex */
            .rx1MinGainIndex = 0,            /* uint8_t rx1MinGainIndex */
            .rx2MaxGainIndex = 195,            /* uint8_t rx2MaxGainIndex */
            .rx2MinGainIndex = 132,            /* uint8_t rx2MinGainIndex */
            .rx1GainDecPin = FR_GPIO_04,
            .rx1GainIncPin = FR_GPIO_05,
            .rx2GainDecPin = FR_GPIO_06,
            .rx2GainIncPin = FR_GPIO_07,
        },
        .rxChannels = FR_RX1RX2,                /* The desired Rx Channels to enable during initialization */
        .rxLoSource = {FR_LO_RF_PLL, FR_LO_RF_PLL},  
    },


    /* Tx settings */
    .tx = 
    {
        .txProfile =
        {
            .txInputRate_kHz = REFCLK_FREQ_KHZ * TX_INRATE_IS_REF_MULT,                    /* Primary Signal BW */            
            .txFir = 
            {
                .gain_dB = FR_FIR_GAIN_0_DB,                        /* filter gain */
                .numFirCoefs = 0,                                   /* number of coefficients in the FIR filter */
                .coefs = NULL
            },
            .txIfConvMode = {FR_IFCONV_BYPASS,FR_IFCONV_BYPASS},
            .txIfConvCfg = {
                {
                .bandAFe = {0},
                .bandABe = {0},
                .bandBFe = {0},
                .bandBBe = {0},
                .bandSel = 0
                },{
                .bandAFe = {0},
                .bandABe = {0},
                .bandBFe = {0},
                .bandBBe = {0},
                .bandSel = 0
                }
            },
            .txMixer = {0}, 
            .rfDirectModeEn={0,0},
            .txFlatnessFir = {
                {
                    .numFirCoefs = TX_FLATNESSCOEFS_LEN,
                    .coefs_II = &txFlatnessFlt_II[0],
                    .coefs_QQ = &txFlatnessFlt_II[0],
                    .coefs_IQ = &txFlatnessFlt_IQ[0],
                    .coefs_QI = &txFlatnessFlt_QI[0],
                },{
                    .numFirCoefs = TX_FLATNESSCOEFS_LEN,
                    .coefs_II = &txFlatnessFlt_II[0],
                    .coefs_QQ = &txFlatnessFlt_II[0],
                    .coefs_IQ = &txFlatnessFlt_IQ[0],
                    .coefs_QI = &txFlatnessFlt_QI[0],
                }
            }       
        },
        .deframerSel = FR_DEFRAMER_A,                    /* FR9009 JESD204b deframer config for the Tx data path */
        .txChannels = FR_TX1TX2,                            /* The desired Tx channels to enable during initialization */
        .txAttenStepSize = FR_TXATTEN_0P05_DB,            /* Tx Attenuation step size */
        .tx1Atten_mdB = 0,                            /* Initial Tx1 Attenuation */
        .tx2Atten_mdB = 0,                            /* Initial Tx2 Attenuation */
        .txLoSource = {FR_LO_RF_PLL, FR_LO_RF_PLL},  
    },


    /* ObsRx settings */
    .obsRx = 
    {
        .orxProfile =
        {
            .rxOutputRate_kHz = REFCLK_FREQ_KHZ * ORX_OUTRATE_IS_REF_MULT,            /* Rx IQ data rate in kHz */
            .rxFir = 
            {
                .gain_dB = FR_FIR_GAIN_0_DB,                /* filter gain */
                .numFirCoefs = 0,                           /* number of coefficients in the FIR filter */
                .coefs = NULL 
            },            
            .rxIfConvMode = {FR_IFCONV_BYPASS,FR_IFCONV_BYPASS},   /* ORx DDC mode */
            .rxIfConvCfg = {
                {  
                    .bandAFe = {0},
                    .bandABe = {0},
                    .bandBFe = {0},
                    .bandBBe = {0},
                    .bandSel = 0                    
                },{                    
                    .bandAFe = {0},
                    .bandABe = {0},
                    .bandBFe = {0},
                    .bandBBe = {0},
                    .bandSel = 0
                }
            },
            .rxMixer = {0},
            .rfDirectModeEn={0,0},
            .rxAdcMode = FR_ADC_IQ2ITLV, 
        },
        .orxGainCtrl = 
        {
            .ORx1Atten_mdB = 0,
            .ORx2Atten_mdB = 0,
        },
        .framerSel = FR_FRAMER_B,                      /* ObsRx JESD204b framer configuration */
        .obsRxChannelsEnable = FR_ORXOFF,                /* The desired ObsRx Channels to enable during initialization */
        .obsRxLoSource = {FR_LO_RF_PLL, FR_LO_RF_PLL},  /* The ORx mixers can use the TX_PLL */
    },

    /* Digital Clock Settings */
    .clocks = 
    {
        .deviceClock_kHz = REFCLK_FREQ_KHZ,            /* CLKPLL and device reference clock frequency in kHz */
        .sysrefDiv =  7680,                            /*!< internal sysref clock divider( from device reference clock)*/
        .clkPllVcoFreq_kHz = REFCLK_FREQ_KHZ * 80,        /* CLKPLL VCO frequency in kHz */
        .clkPllHsDiv = 5,                       /* CLKPLL high speed clock divider */
        .rfPllUseExternalLo = 0,                /* 1= Use external LO for RF PLL, 0 = use internal LO generation for RF PLL */
        .rfPllPhaseSyncMode = FR_RFPLLMCS_NOSYNC,               /* RFPLL MCS (Phase sync) mode */
        .rfpllFreq_hz = 2354720000,
        .orfpllFreq_hz = 0,
        .bbpllStatusGpio={
            .en = 0,
            .gpio_num = 0,
        },
        .rfpllStatusGpio={
            .en = 0,
            .gpio_num = 0,
        },
        .orfpllStatusGpio={
            .en = 0,
            .gpio_num = 0,
        },
    },

    /* JESD204B settings */
    .jesd204Settings = 
    {
        /* Framer A settings */
        .framerA = 
        {
            .bankId = 1,                    /* JESD204B Configuration Bank ID -extension to Device ID (Valid 0..15) */
            .deviceId = 0,                    /* JESD204B Configuration Device ID - link identification number. (Valid 0..255) */
            .lane0Id = 0,                    /* JESD204B Configuration starting Lane ID.  If more than one lane used, each lane will increment from the Lane0 ID. (Valid 0..31) */
            .M = 4,                            /* number of ADCs (0, 2, or 4) - 2 ADCs per receive chain */
            .K = 32,                        /* number of frames in a multiframe (default=32), F*K must be a multiple of 4. (F=2*M/numberOfLanes) */
            .F = 4,                            /* F (number of bytes per frame) */
            .Np = 16,                            /* Np (converter sample resolution) */
            .scramble = 1,                    /* scrambling off if framerScramble= 0, if framerScramble>0 scramble is enabled. */
            .externalSysref = 1,            /* 0=use internal SYSREF, 1= use external SYSREF */
            .serializerLanesEnabled = 0x03,    /* serializerLanesEnabled - bit per lane, [0] = Lane0 enabled, [1] = Lane1 enabled */
            .serializerLaneCrossbar = 0xE4,    /* serializerLaneCrossbar */
            .lmfcOffset = 0,                /* lmfcOffset - LMFC offset value for deterministic latency setting */
            .syncbInSelect = 0,                /* syncbInSelect; */
            .syncbInLvdsMode = 1,
            .syncbInLvdsPnInvert = 0,
            .enableManualLaneXbar = 1, /* 0=auto, 1=manual */
            .MFdisableCharReplacement = 0,      /*0:多帧边界按照204B规范，对重复的数据进行K码替换， 1:多帧边界不进行K码替换 */
            .sysrefDisable = 0,                 /*0：FrameA/B 正常监测外部sysref 1：不使用外部sysref信号*/
            .sysrefOneShot = 0,                 /*0: 按照正常的建链要求，持续监测sysref 1：建链过程只要求监测到一次sysref信号*/
        },
        /* Framer B settings */
        .framerB = 
        {
            .bankId = 0,                    /* JESD204B Configuration Bank ID -extension to Device ID (Valid 0..15) */
            .deviceId = 0,                    /* JESD204B Configuration Device ID - link identification number. (Valid 0..255) */
            .lane0Id = 0,                    /* JESD204B Configuration starting Lane ID.  If more than one lane used, each lane will increment from the Lane0 ID. (Valid 0..31) */
            .M = 2,                            /* number of ADCs (0, 2, or 4) - 2 ADCs per receive chain */
            .K = 32,                        /* number of frames in a multiframe (default=32), F*K must be a multiple of 4. (F=2*M/numberOfLanes) */
			.F = 4,                            /* F (number of bytes per frame) */
            .Np = 16,                            /* Np (converter sample resolution) */
            .scramble = 1,                    /* scrambling off if framerScramble= 0, if framerScramble>0 scramble is enabled. */
            .externalSysref = 1,            /* 0=use internal SYSREF, 1= use external SYSREF */
            .serializerLanesEnabled = 0x0C,    /* serializerLanesEnabled - bit per lane, [0] = Lane0 enabled, [1] = Lane1 enabled */
            .serializerLaneCrossbar = 0xE4,    /* serializerLaneCrossbar */
            .lmfcOffset = 0,                /* lmfcOffset - LMFC offset value for deterministic latency setting */
            .syncbInSelect = 0,                /* syncbInSelect; */
            .syncbInLvdsMode = 1,
            .syncbInLvdsPnInvert = 0,
            .enableManualLaneXbar = 1, /* 0=auto, 1=manual */
            .MFdisableCharReplacement = 0,      /*0:多帧边界按照204B规范，对重复的数据进行K码替换， 1:多帧边界不进行K码替换 */
            .sysrefDisable = 0,                 /*0：FrameA/B 正常监测sysref 1：不使用sysref信号*/
            .sysrefOneShot = 0,                 /*0: 按照正常的建链要求，持续监测sysref 1：建链过程只要求监测到一次sysref信号*/
        },
        /* Deframer A settings */
        .deframerA = 
        {
            .bankId = 0,                    /* bankId extension to Device ID (Valid 0..15) */
            .deviceId = 0,                    /* deviceId  link identification number. (Valid 0..255) */
            .lane0Id = 0,                    /* lane0Id Lane0 ID. (Valid 0..31) */
            .M = 4,                            /* M  number of DACss (0, 2, or 4) - 2 DACs per transmit chain */
            .K = 32,                        /* K  #frames in a multiframe (default=32), F*K=multiple of 4. (F=2*M/numberOfLanes) */
            .scramble = 1,                    /* scramble  scrambling off if scramble= 0 */
            .externalSysref = 0,            /* externalSysref  0= use internal SYSREF, 1= external SYSREF */
            .deserializerLanesEnabled = 0x0F,    /* deserializerLanesEnabled  bit per lane, [0] = Lane0 enabled */
            .deserializerLaneCrossbar = 0xE4,    /* deserializerLaneCrossbar */
            .lmfcOffset = 0,                /* lmfcOffset	 LMFC offset value to adjust deterministic latency */
            .syncbOutSelect = 0,                /* SYNCBOUT0/1 select */
            .Np = 16,                /* Np (converter sample resolution) */
            .syncbOutLvdsPnInvert = 0,
            .enableManualLaneXbar = 1, /* 0=auto, 1=manual */
            .sysrefDisable = 0,                 /*0：FrameA/B 正常监测外部sysref 1：不使用外部sysref信号*/
            .sysrefOneShot = 0,                 /*0: 按照正常的建链要求，持续监测sysref 1：建链过程只要求监测到一次sysref信号*/
        },
        .serAmplitude = 15,                    /* Serializer amplitude setting. Default = 15. Range is 0..15 */
        .serPreEmphasis = 3,                /* Serializer pre-emphasis setting. Default = 1 Range is 0..4 */
        .serInvertLanePolarity = 0,            /* Serializer Lane PN inversion select. Default = 0. Where, bit[0] = 1 will invert lane [0], bit[1] = 1 will invert lane 1, etc. */
        .desInvertLanePolarity = 0,            /* Deserializer Lane PN inversion select.  bit[0] = 1 Invert PN of Lane 0, bit[1] = Invert PN of Lane 1, etc */
        .desEqSetting = 5,                    /* Deserializer Equalizer setting. Applied to all deserializer lanes. Range is 0..7 */
        .sysrefLvdsMode = 1,                /* Use LVDS inputs on FR9009 for SYSREF */
        .sysrefLvdsPnInvert = 0              /*0= Do not PN invert SYSREF */
    },
    .fhm={
        .fhm_rx_ch = 0xff,  /*0xff表示程序根据开启通道进行配置*/
        .fhm_orx_ch = 0xff,
        .fhm_tx_ch = 0xff,
        .fhmEnable = FHM_MODE_EN,
        .fhmType = FHM_TYPE,
        .fhmSwitchFreq_Hz = FHM_SWITCH_FREQ_HZ,
        .predict_cali = PREDICT_CALI_ENALBE,
        .fhmRf ={
            .fhmGpioPin = FHM_RF_TRIGGER_PIN_NUM,
            .fhmTriggerMode = FHM_RF_TRIGGER_MODE,
            .caliFreqNums = PRE_CALI_FREQ_LEN,
            .calibrationFrequencyList_KHz = rfpreCaliFreqs_khz,
            .fhmFreqNums = FHM_RF_LEN,
            .fhmFrequencyList_KHz = FhmRfFreqs_khz,
        },
        .fhmORf = {
            .fhmGpioPin = FHM_ORF_TRIGGER_PIN_NUM,
            .fhmTriggerMode = FHM_ORF_TRIGGER_MODE,
            .caliFreqNums = PRE_CALI_FREQ_LEN,
            .calibrationFrequencyList_KHz = rfpreCaliFreqs_khz,
            .fhmFreqNums = FHM_ORF_LEN,
            .fhmFrequencyList_KHz = FhmORfFreqs_khz,
        },
        .rx_nco={
            .fhmGpioPin = FHM_RF_TRIGGER_PIN_NUM,
            .fhmTriggerMode = FHM_RF_TRIGGER_MODE,
            .ch = 0x3,
            .fhmFreqNums = 0,//FHM_RX_NCO_LEN,
            .fhmFrequencyList_KHz = rxNcoFreqs,
            .fhmGpioPin = 0,
            .fhmTriggerMode = FR_FHM_NON_GPIO_MODE,
        },
        .tx_nco={
            .fhmGpioPin = FHM_ORF_TRIGGER_PIN_NUM,
            .fhmTriggerMode = FHM_ORF_TRIGGER_MODE,
            .ch = 0x3,
            .fhmFreqNums = FHM_TX_NCO_LEN,
            .fhmFrequencyList_KHz = txNcoFreqs,
            .fhmGpioPin = 0,
            .fhmTriggerMode = FR_FHM_NON_GPIO_MODE,
        }

    }
};

//Only needs to be called if user wants to setup AGC parameters
fr9009AgcCfg_t rxAgcCtrl =
{
    .agcPeakWaitTime				= 6,
    .agcRx1MaxGainIndex				= 63,
    .agcRx1MinGainIndex				= 0,
    .agcRx2MaxGainIndex				= 195,
    .agcRx2MinGainIndex				= 132,
    .agcGainUpdateCounter_us		= 3, /*30720,*/  /* AGC gain update time in us (125us-250us - based on IQ data rate - set for 125us @ 245.76 Mhz) */
    .agcRx1AttackDelay				= 6,
    .agcRx2AttackDelay				= 6,
    .agcSlowLoopSettlingDelay		= 16,
    .agcLowThreshPreventGain		= 0,
    .agcChangeGainIfThreshHigh		= 1,
    .agcPeakThreshGainControlMode	= 0,    /** 0: prak/power mode 1:peak mode*/
    .agcResetOnRxon					= 1,
    .agcEnableSyncPulseForGainCounter= 0,
    .agcEnableFastRecoveryLoop		= 1,          /*!<1- bit field to enable the multiple time constants in AGC loop for fast attack and fast recovery to max gain. */
    /* agcPower */
    {
        .powerEnableMeasurement				 = 0,      /*!<1-bit field, enables the Rx power measurement block. */
        .powerUseRfirOut				     = 0,      /*!<1-bit field, allows using Rx PFIR for power measurement. */
        .powerUseBBDC2						 = 0,      /*!<1-bit field, allows to use the output of the second digital offset block in the Rx datapath for power measurement. */
        .underRangeHighPowerThresh			 = 18,      /*!<AGC power measurement detect lower 0 threshold. Default = -20dBFS == 20,Valid Range from 1 to 80. 1 == -1dBFS */
        .underRangeLowPowerThresh			 = 23,      /*!<AGC power measurement detect lower 1 threshold. Default = -26dBFS == 26, Valid Range from 1 to 80. 1 == -1dBFS */
        .underRangeHighPowerGainStepRecovery = 10,      /*!<AGC power measurement detect lower 0 recovery gain step. Default = 2dB - based on gain table step  size, 5-bit register value where max = 0x1F, min = 0x00 */
        .underRangeLowPowerGainStepRecovery	 = 20,      /*!<AGC power measurement detect lower 1 recovery gain step. Default = 4dB - based on gain table step size, 5-bit register value where max = 0x1F, min = 0x00 */
        .powerMeasurementDuration			 = 8,      /*!< Average power measurement duration = 2^powerMeasurementDuration datapath clk(1/(4*ref @ bb = ref * 80)). Valid range from 2 to 20 */
        .rx1TddPowerMeasDuration			 = 14,      /*!<Allows power detection of data for a specific slice of the gain update counter. 16-bit register value (currently not used) */
        .rx1TddPowerMeasDelay				 = 8,      /*!<Allows power detection of data for a specific slice of the gain update counter. 16-bit register value (currently not used) */
        .rx2TddPowerMeasDuration			 = 14,      /*!<Allows power detection of data for a specific slice of the gain update counter. 16-bit register value (currently not used) */
        .rx2TddPowerMeasDelay				 = 8,      /*!<Allows power detection of data for a specific slice of the gain update counter. 16-bit register value (currently not used) */
        .upper0PowerThresh					 = 3,      /*!<AGC upper 0 (overRangeHighPowerThreshold) threshold for power measurement.Default = -3dBFS == 3, Valid Range from 1 to 80. 1 == -1dBFS*/
        .upper1PowerThresh					 = 10,      /*!< AGC upper 1 (overRangeLowPowerThreshold)  threshold for power measurement. Default = -10dBFS == 10, Valid Range from 1 to 80. 1 == -1dBFS*/
        .powerLogShift						 = 4,
	    .overRangeLowPowerGainStepAttack	 = 16,	/*overRangeLowPowerGainStepAttack*/
	    .overRangeHighPowerGainStepAttack	 = 8	/*overRangeHighPowerGainStepAttack*/
    },
    /* agcPeak */
    {
        .agcUnderRangeLowInterval_ns	= 50,        /*!<1st update interval for the multiple time constant in AGC loop mode, Default:50. */
        .agcUnderRangeMidInterval		= 0,          /*!<2nd update interval for multiple time constant AGC mode. Calculated as (agcUnderRangeMidInterval+1)*agcUnderRangeLowInterval_ns. Valid range is 0 to 63, default 0 */
        .agcUnderRangeHighInterval		= 0,          /*!<sets the 3rd update interval for the multiple time constant in AGC loop mode. Calculated as a multiple of agcUnderRangeMidInterval and agcUnderRangeLowInterval, Default: 4 */
        .apdHighThresh					= 39,/*25,*/ /*39,*/         /*!<AGC APD high threshold. Default=0x1F, 6-bit register value where max=0x3F, min =0x00 */
        .apdLowGainModeHighThresh		= 49,         /*!<AGC APD peak detect high threshold. default = 0x1F, 6-bit register value where max = 0x3F, min = 0x00.  Set to 3dB below apdHighThresh */
        .apdLowThresh					= 23,/*15,*/ /*23,*/         /*!<AGC APD peak detect low threshold. default = 3dB below high threshold, 6-bit register value where max =0x3F, min = 0x00 */
        .apdLowGainModeLowThresh		= 19,         /*!<AGC APD peak detect low threshold. default = 3dB below high threshold, 6-bit register value where max = 0x3F, min = 0x00 . Set to 3dB below apdLowThresh  */
        .apdUpperThreshPeakExceededCnt	= 0xff,          /*!<AGC APD peak detect upper threshold count. Default = 0x06 8-bit register value where max = 0xFF, min = 0x20  */
        .apdLowerThreshPeakExceededCnt	= 0xff,          /*!<AGC APD peak detect lower threshold count. Default = 0x03, 8-bit register value where max = 0xFF, min = 0x00  */
        .apdGainStepAttack				= 2,          /*!<AGC APD peak detect attack gain step. Default = 2dB step - based on gain table step size, 5-bit register  value, where max = 0x1F, min = 0x00  */
        .apdGainStepRecovery			= 0,          /*!<AGC APD gain index step size. Recommended to be same as hb2GainStepRecovery. Default = 0x00, 5-bit register value where max = 0x1F, min = 0x00  */
        .enableHb2Overload				= 1,          /*!<1-bit field, enables or disables the HB2 overload detector.  */
        .hb2OverloadDurationCnt			= 1,          /*!<3-bit field. Sets the window of clock cycles (at the HB2 output rate) to meet the overload count. */
        .hb2OverloadThreshCnt			= 1,          /*!<4-bit field. Sets the number of actual overloads required to trigger the overload signal.  */
        .hb2HighThresh					    = 5805,        /*!<AGC HB2 output high threshold. Valid range from  0 to 2^13, default = -6 dBFs  8192* squrt(2) * 10^(-6/20) = -6 dBfs*/
        .hb2UnderRangeLowThresh			    = 291,         /*!<AGC HB2 output low threshold. Valid range from  0 to 2^13, deflault = -32 dBFs */
        .hb2UnderRangeMidThresh			    = 1158,         /*!< AGC HB2 output low threshold for 2nd interval for multiple time constant AGC mode. Valid range from  0 to 2^13,default = -20 dBFs */
        .hb2UnderRangeHighThresh			= 2311,        /*!<AGC HB2 output low threshold for 3rd interval for multiple time constant AGC mode. Valid range from  0 to 2^13, default = -14 dBFs */
        .hb2UpperThreshPeakExceededCnt	= 6,          /*!<AGC HB2 output upper threshold count. Default = 0x06, 8-bit register value where max = 0xFF, min =  0x20 */
        .hb2LowerThreshPeakExceededCnt	= 3,          /*!<AGC HB2 output lower threshold count. Default = 0x03, 8-bit register value where max = 0xFF, min = 0x00 */
        .hb2GainStepHighRecovery		= 4,          /*!<AGC HB2 gain index step size. Valid range from  0 to 31, step（default） power should < (High-UnderRangeHigh)/2*/
        .hb2GainStepLowRecovery			= 16,          /*!<AGC HB2 gain index step size, when the HB2 Low Overrange interval 2 triggers. Valid range from  0 to 31*/
        .hb2GainStepMidRecovery			= 8,          /*!<AGC HB2 gain index step size, when the HB2 Low Overrange interval 3 triggers. Valid range from  0 to 31, step（default） power should < (High-hb2UnderRangeMidThresh) - 3 */
        .hb2GainStepAttack				= 4,          /*!<AGC HB2 output attack gain step. Valid range from  0 to 31 ,step（default 0.5db） power should < (High-UnderRangeHigh) - 1 */
        .hb2OverloadPowerMode			= 1,
        .hb2OvrgSel						= 0,
        .hb2ThreshConfig					= 3,
        .hb2UnderRangeLowThreshExceededCnt= 0,
        .hb2UnderRangeMidThreshExceededCnt= 0
    }
};


