#include "custom_cfg.h"

short g_phy_select = 0;
rf_chip_phy_t g_phy_obj[RF_PHY_NUMBER];
chip_config_t g_phy_config[RF_PHY_NUMBER] = 
{
    //chip 0
    {
        .mode = CH1_CH2_TDD,
        .use_bybrid_mode = 0,
        .hybrid_mode = HYBRID_FDD_SXTX,
        .dig_if = LVDS_IF,
        .p0p1_port = DUAL_PORT,
        .data_rate = DDR,
        .tx_port[0] = TX_A,
        .tx_port[1] = TX_A,
        .rx_port[0] = MIXA_DIFF,
        .rx_port[1] = MIXA_DIFF,
        .bandwidth = BW_LTE100,
        .xtal_freq = 30720000UL,//64000000UL,
        .sys_fvco = 2949120000ULL,//3072000000ULL,
        .x4_enable = 0,
        .rx_flo = 2800000000ULL,
        .tx_flo = 2800000000ULL,
        .core2_enable = 0,
        .rx_ext_loop = 0,
        .tx_ext_loop = 0,
        .qec_dbfs = 10,
        .lol_dbfs = 10,
        .lvds_cal_flag = 0,
        .auxadc1_cal_flag = 1,
        .r_cal_flag = 1,
        .tx_atten_chn_flag = 0,
        .rx_bw_cal_flag = 1,
        .tx_bw_cal_flag = 1,
        .rx_dc_cal_flag = 1,
        .rx_qec_flag = 1,
        .tx_dc_cal_flag = 1,
        .tx_dac_cal_flag = 1,
        .tx_qec_flag = 1,
        .vco_range_cal_flag = 1,
        .sx_cal_flag = 0,
        .txlo_cal_flag = 0,
        .lo_change_mode = LO_CHANGE_FAST_LOCK_ATTACH_TRX_LO,
        .wire_control_en = 1,
        .wire_ctrl = PULSE_CTRL,
        .gain_table_mode = SPLIT_TBL,
        .gain_ctrl_mode = MANUAL_CTRL,
        .gain_ctrl_pin_flag = 0,
        .custom_bandwidth_flag = 0,
        .custom_bandwidth = 50000000UL,//50M
        .syspll_cfg_flag = 0,
        .bb_sample_rate = 92160000,
        .dac_syspll_lo_div = 0x0b,
        .adc_syspll_lo_div = 0x0b,
        .chip_sel = 0,
        .rxgain_force_valid_flag = 1,
        .ldo_cal_flag = 1,
        .sx_vco_ldo = 1200,
        .sxlf_ldo = 1200,
        .syspll_ldo = 1070,
        .txabb_ldo = 1200,
        .txdac_ldo = 1080,
        .txfe_ldo = 1200,
        .txsx_lo_ldo = 1200,
        .rxadc_ldo = 1200,
        .rxfe_ldo = 1250,
        .rxsx_lo_ldo = 1200,
        .mdig_ldo = 1150,
        .reg901_val = 0xd0,
        .reg639_620_bit1 = 0x01,
        .reg61A_val = 0x4f,
        .reg600_val = 0x03,
        .reg602_val = 0x02,
        .scap_min = 0,
        .scap_max = 2047,
        .scap_cnt = 11,
        .vol_low_limit = 250,
        .vol_up_limit = 850,
        .vol_margin = 100,
        .trx_lo_cal_mode = TRX_LO_HYBRID_CAL,
        .RxDc_Offset_Ver = 2,
        .Rx_ImBalance_cal_flag = 0,
        .imb_rx_cfg[0][0] = 0xbc,
        .imb_rx_cfg[0][1] = 0x1a,
        .imb_rx_cfg[1][0] = 0xbc,
        .imb_rx_cfg[1][1] = 0x1a,
        .lo_leakage_cal_flag = 0,
        .qec_try_num = 1,
        .qec_dc_remove_mode = 1,
        .qec_debug_level = 1,
    },

    //chip 1
    {
        .mode = CH1_CH2_FDD,
        .use_bybrid_mode = 0,
        .hybrid_mode = HYBRID_FDD_SXTX,
        .dig_if = LVDS_IF,
        .p0p1_port = DUAL_PORT,
        .data_rate = DDR,
        .tx_port[0] = TX_A,
        .tx_port[1] = TX_A,
        .rx_port[0] = MIXA_DIFF,
        .rx_port[1] = MIXA_DIFF,
        .bandwidth = BW_LTE20,
        .xtal_freq = 30720000UL,//64000000UL,
        .sys_fvco = 2949120000ULL,//3072000000ULL,
        .x4_enable = 0,
        .rx_flo = 2800000000ULL,
        .tx_flo = 2300000000ULL,
        .core2_enable = 0,
        .rx_ext_loop = 0,
        .tx_ext_loop = 0,
        .qec_dbfs = 10,
        .lol_dbfs = 10,
        .lvds_cal_flag = 0,
        .auxadc1_cal_flag = 1,
        .r_cal_flag = 1,
        .tx_atten_chn_flag = 0,
        .rx_bw_cal_flag = 1,
        .rx_dc_cal_flag = 1,
        .rx_qec_flag = 1,
        .tx_dc_cal_flag = 1,
        .tx_dac_cal_flag = 1,
        .tx_qec_flag = 1,
        .vco_range_cal_flag = 1,
        .sx_cal_flag = 0,
        .txlo_cal_flag = 0,
        .lo_change_mode = LO_CHANGE_FAST_LOCK_ATTACH_TRX_LO,
        .wire_control_en = 1,
        .wire_ctrl = PULSE_CTRL,
        .gain_table_mode = SPLIT_TBL,
        .gain_ctrl_mode = MANUAL_CTRL,
        .gain_ctrl_pin_flag = 0,
        .custom_bandwidth_flag = 0,
        .custom_bandwidth = 50000000UL,//50M
        .syspll_cfg_flag = 0,
        .bb_sample_rate = 92160000,
        .dac_syspll_lo_div = 0x0b,
        .adc_syspll_lo_div = 0x0b,
        .chip_sel = 1,
        .rxgain_force_valid_flag = 1,
        .ldo_cal_flag = 1,
        .sx_vco_ldo = 1200,
        .sxlf_ldo = 1200,
        .syspll_ldo = 1070,
        .txabb_ldo = 1200,
        .txdac_ldo = 1080,
        .txfe_ldo = 1200,
        .txsx_lo_ldo = 1200,
        .rxadc_ldo = 1200,
        .rxfe_ldo = 1250,
        .rxsx_lo_ldo = 1200,
        .mdig_ldo = 1150,
        .reg901_val = 0xd0,
        .reg639_620_bit1 = 0x01,
        .reg61A_val = 0x4f,
        .reg600_val = 0x03,
        .reg602_val = 0x02,
        .scap_min = 0,
        .scap_max = 2047,
        .scap_cnt = 11,
        .vol_low_limit = 250,
        .vol_up_limit = 850,
        .vol_margin = 100,
        .trx_lo_cal_mode = TRX_LO_HYBRID_CAL,
        .RxDc_Offset_Ver = 2,
        .Rx_ImBalance_cal_flag = 0,
        .imb_rx_cfg[0][0] = 0xbc,
        .imb_rx_cfg[0][1] = 0x1a,
        .imb_rx_cfg[1][0] = 0xbc,
        .imb_rx_cfg[1][1] = 0x1a,
        .lo_leakage_cal_flag = 0,
        .qec_try_num = 1,
        .qec_dc_remove_mode = 1,
        .qec_debug_level = 1,
    },
};

RX_GCTRL_CFG_T gctrl_dflt_cfg = 
{
    .basic.cfg_agc_mode                         = 0, // mgc mode
    .basic.cfg_gain_table_mode                  = 0, // full table
    .basic.cfg_pin_pls_gain_change_sel          = 0,
    .delay.cfg_init_setting_delay               = 10,
    .delay.cfg_pdt_setting_delay                = 20,
    .delay.cfg_hbf_setting_delay                = 30,
    .ext_lna.cfg_split_ext_lna_ena              = 0 ,
    .ext_lna.cfg_split_ext_lna_db               = 22,
    .ext_lna.cfg_split_ext_lna_polarity         = 0 ,
    .ext_lna.cfg_split_ext_lna_inc_th           = 22,
    .ext_lna.cfg_split_ext_lna_dec_th           = 18,
    .ext_lna.cfg_split_ext_lna_force_ena        = 0 ,
    .ext_lna.cfg_split_ext_lna_force_index      = 0 ,

    // Full gain table setting
    .gain_full.max_index                        = 42,
    .gain_full.init_index                       = 42,

    // SPLIT GAIN TABLE setting
    .gain_split.cfg_split_lmt_index_limit       = 5,
    .gain_split.cfg_split_lna_index_limit       = 0,
    .gain_split.cfg_split_init_lna_index        = 0,
    .gain_split.cfg_split_init_lmt_index        = 5,
    .gain_split.cfg_split_init_lpf_index        = 12,

    // DIGITAL AGC setting
    .gain_digital.cfg_digital_gain_ena          = 0,
    .gain_digital.cfg_digital_init_index        = 0,
    .gain_digital.cfg_digital_max_index         = 200,

    // LMT peak dectector
    .lmt_pdt.cfg_lmt_setting_counter            = 2,
    .lmt_pdt.cfg_lmt_overload_ena               = 1,
    .lmt_pdt.cfg_lmt_prevent_inc_ena            = 1,
    .lmt_pdt.cfg_lmt_underload_ena              = 0,
    .lmt_pdt.cfg_lmt_overload_threshold         = 180,
    .lmt_pdt.cfg_lmt_prevent_inc_threshold      = 160,
    .lmt_pdt.cfg_lmt_underload_threshold        = 120,
    .lmt_pdt.cfg_lmt_overload_exceed_counter    = 20,
    .lmt_pdt.cfg_lmt_prevent_exceed_counter     = 20,
    .lmt_pdt.cfg_lmt_underload_exceed_counter   = 255,
    .lmt_pdt.cfg_lmt_overload_power_coeff       = 0,
    .lmt_pdt.cfg_lmt_underload_power_coeff      = 3,

    // ADC peak detector
    .adc_pdt.cfg_adc_overload_lg_ena            = 1,
    .adc_pdt.cfg_adc_overload_sm_ena            = 1,
    .adc_pdt.cfg_adc_prevent_inc_ena            = 1,
    .adc_pdt.cfg_adc_underload_ena              = 0,
    .adc_pdt.cfg_adc_overload_lg_threshold      = 250,
    .adc_pdt.cfg_adc_overload_sm_threshold      = 240,
    .adc_pdt.cfg_adc_prevent_inc_threshold      = 230,
    .adc_pdt.cfg_adc_underload_threshold        = 20,
    .adc_pdt.cfg_adc_overload_lg_exceed_counter = 250,
    .adc_pdt.cfg_adc_overload_sm_exceed_counter = 250,
    .adc_pdt.cfg_adc_prevent_inc_exceed_counter = 120,
    .adc_pdt.cfg_adc_underload_exceed_counter   = 255,
    .adc_pdt.cfg_adc_overload_power_coeff       = 2,
    .adc_pdt.cfg_adc_underload_power_coeff      = 3,

    // HBF power measurement\low powr detector\digital overeflow detect
    .hbf_pwr.cfg_hbf_avp_ena                    = 1,
    .hbf_pwr.cfg_hbf_avp_meas_num               = 10,
    .hbf_lpwr.cfg_hbf_low_pwr_ena               = 0,
    .hbf_lpwr.cfg_hbf_low_pwr_th                = 50,
    .hbf_lpwr.cfg_hbf_low_pwr_meas_num          = 8,
    .hbf_ovf.cfg_hbf_ovf_ena                    = 0,
    .hbf_ovf.cfg_hbf_ovf_exceed_threshold       = 200,

    // MGC default setting
    .mgc.cfg_mgc_mode                           = 0,
    .mgc.cfg_mgc_inc_step                       = 0,
    .mgc.cfg_mgc_dec_step                       = 0,
    .mgc.cfg_mgc_adj_gain_pos_auto              = 1,
    .mgc.cfg_mgc_adj_gain_pos_lmt               = 0,

    // slow attack AGC default setting
    .agc_slow.cfg_slow_calc_time                         = 7,
    .agc_slow.cfg_slow_pin_sync_ena                      = 0,
    .agc_slow.cfg_slow_pdt_clear_mode                    = 1,
    .agc_slow.cfg_slow_hbf_overflow_quick_resp           = 1,
    .agc_slow.cfg_slow_lmt_overload_quick_resp           = 1,
    .agc_slow.cfg_slow_lmt_underload_quick_resp          = 0,
    .agc_slow.cfg_slow_adc_overload_lg_quick_resp        = 1,
    .agc_slow.cfg_slow_adc_overload_sm_quick_resp        = 1,
    .agc_slow.cfg_slow_adc_underload_quick_resp          = 0,
    .agc_slow.cfg_slow_agc_gain_update_mode_ena          = 1,
    .agc_slow.cfg_slow_agc_gain_update_counter           = 307200,
    .agc_slow.cfg_slow_full_lmt_overload_step            = 0,
    .agc_slow.cfg_slow_full_lmt_underload_step           = 0,
    .agc_slow.cfg_slow_full_adc_overload_step            = 0,
    .agc_slow.cfg_slow_full_adc_underload_step           = 0,
    .agc_slow.cfg_slow_full_hbf_overflow_step            = 4,
    .agc_slow.cfg_slow_agc_outter_high_step              = 3,
    .agc_slow.cfg_slow_agc_inner_high_step               = 1,
    .agc_slow.cfg_slow_agc_inner_low_step                = 1,
    .agc_slow.cfg_slow_agc_outter_low_step               = 3,
    .agc_slow.cfg_slow_split_lmt_dec_step                = 0,
    .agc_slow.cfg_slow_split_lpf_dec_step                = 0,
    .agc_slow.cfg_slow_split_dig_dec_step                = 4,
    .agc_slow.cfg_slow_split_lmt_inc_step                = 0,
    .agc_slow.cfg_slow_split_lpf_inc_step                = 0,
    // set target  to -9 ~ -11 dBfs
    .agc_slow.cfg_slow_agc_outter_high_th                = 6,
    .agc_slow.cfg_slow_agc_inner_high_th                 = 9,
    .agc_slow.cfg_slow_agc_inner_low_th                  = 11,
    .agc_slow.cfg_slow_agc_outter_low_th                 = 18,

    // fast attack AGC default setting
    .agc_fast.cfg_fast_calc_time                         = 8,
    .agc_fast.cfg_fast_s1_exit_counter                   = 50,
    .agc_fast.cfg_fast_s1_full_large_dec_step            = 6,
    .agc_fast.cfg_fast_s1_full_medium_dec_step           = 5,
    .agc_fast.cfg_fast_s1_full_small_dec_step            = 3,
    .agc_fast.cfg_fast_s1_split_lmt_dec_step             = 0,
    .agc_fast.cfg_fast_s1_split_lpf_dec_step             = 1,
    .agc_fast.cfg_fast_s1_split_dig_dec_step             = 0,
    .agc_fast.cfg_fast_s2_adjustment_method              = 2,
    .agc_fast.cfg_fast_s2_lock_power_target              = 24, // 0.5dB / unit
    .agc_fast.cfg_fast_s2_max_inc_step                   = 50,
    .agc_fast.cfg_fast_s2_to_s2a_mask                    = 0,
    .agc_fast.cfg_fast_s2_limit_max_adj_step_ena         = 0,
    .agc_fast.cfg_fast_s2_to_s2b_mask                    = 0,
    .agc_fast.cfg_fast_s2a_exit_counter                  = 100,
    .agc_fast.cfg_fast_s2a_inc_step                      = 1,
    .agc_fast.cfg_fast_s2b_to_s2a_mask                   = 0,
    .agc_fast.cfg_fast_s2b_exit_counter                  = 100,
    .agc_fast.cfg_fast_s3_overrange_counter              = 10,
    .agc_fast.cfg_fast_s3_confirm_counter                = 10,
    .agc_fast.cfg_fast_s3_dec_step                       = 0,
    .agc_fast.cfg_fast_s3_to_s2a_mask                    = 0,
    .agc_fast.cfg_fast_s4_avp_meas_num                   = 4,
    .agc_fast.cfg_fast_unlock_mode_energy_lost           = 0,
    .agc_fast.cfg_fast_unlock_mode_exist_rx              = 0,
    .agc_fast.cfg_fast_unlock_mode_pin_ena               = 0,
    .agc_fast.cfg_fast_unlock_mode_spi                   = 0,
    .agc_fast.cfg_fast_set_gain_burst_start_sel          = 0,
    .agc_fast.cfg_fast_opt_gain_offset                   = 0,
    .agc_fast.cfg_fast_dont_unlock_lmt_pdt_overload      = 0,
    .agc_fast.cfg_fast_dont_unlock_adc_pdt_overload_lg   = 0,
    .agc_fast.cfg_fast_dont_unlock_lmt_pdt_underload     = 0,
    .agc_fast.cfg_fast_dont_unlock_adc_pdt_underload     = 0,
    .agc_fast.cfg_fast_dont_unlock_energy_lost           = 0,
    .agc_fast.cfg_fast_dont_unlock_energy_boost          = 0,
    .agc_fast.cfg_fast_dont_unlock_pin_agc_ena           = 0,
    .agc_fast.cfg_fast_energy_lost_threshold_db          = 0,
    .agc_fast.cfg_fast_energy_boost_threshold_db         = 0,
    .agc_fast.cfg_fast_energy_change_exit_counter        = 0,
    .agc_fast.cfg_fast_gain_lock_hold_time               = 0,
    
};

RX_DC_TRACK_CFG dc_track_cfg = {
    .cfg_raw_sample_num        = 1000  ,
    .cfg_fine_sample_num       = 2000  ,
    .cfg_dc_thrd_raw           = 8000  ,
    .cfg_dc_thrd_fine[0]       = 14000 ,
    .cfg_dc_thrd_fine[1]       = 14000 ,
    .cfg_dc_thrd_fine[2]       = 14000 ,
    .cfg_dc_thrd_fine[3]       = 14000 ,
    .cfg_dc_thrd_fine[4]       = 14000 ,
    .cfg_dc_thrd_fine[5]       = 14000 ,
    .cfg_update_exit_counter   = 200 ,
    .cfg_hold_exit_counter     = 10  ,
    .cfg_interval_detect       = 100 ,
    .cfg_interval_update       = 2000,
    .cfg_track_dig_offset      = 1   , 
    .cfg_dc_tracking_mode      = 1   ,
    .cfg_tdd_mode               = 0     ,
};


/* rx gain: full table */
uint8_t g_rx_gain_full_table[43][3] = 
{
    {0, 0, 0},
    {0, 0, 1},
    {0, 0, 2},
    {0, 0, 3},
    {0, 0, 4},
    {0, 0, 5},
    {0, 1, 0},
    {0, 1, 1},
    {0, 1, 2},
    {0, 1, 3},
    {0, 1, 4},
    {0, 1, 5},
    {0, 2, 0},
    {0, 2, 1},
    {0, 2, 2},
    {0, 2, 3},
    {0, 2, 4},
    {0, 2, 5},
    {0, 3, 0},
    {0, 3, 1},
    {0, 3, 2},
    {0, 3, 3},
    {0, 3, 4},
    {0, 3, 5},
    {0, 4, 0},
    {0, 4, 1},
    {0, 4, 2},
    {0, 4, 3},
    {0, 4, 4},
    {0, 4, 5},
    {0, 5, 0},
    {0, 5, 1},
    {0, 5, 2},
    {0, 5, 3},
    {0, 5, 4},
    {0, 5, 5},
    {0, 5, 6},
    {0, 5, 7},
    {0, 5, 8},
    {0, 5, 9},
    {0, 5, 10},
    {0, 5, 11},
    {0, 5, 12},
};


/* tx gain */
uint8_t g_tx_gain_index[51][2] =
{
    /* PA_Gain_Index   BB_Gain_Index   */
    // At   uation(dB) = PA_Gain_Index * 3 + BB_Gain_Index
    {0, 0   },
    {0, 1   },
    {0, 2   },
    {0, 3   },
    {0, 4   },
    {0, 5   },
    {1, 3   },
    {1, 4   },
    {1, 5   },
    {2, 3   },
    {2, 4   },
    {2, 5   },
    {3, 3   },
    {3, 4   },
    {3, 5   },
    {4, 3   },
    {4, 4   },
    {4, 5   },
    {5, 3   },
    {5, 4   },
    {5, 5   },
    {6, 3   },
    {6, 4   },
    {6, 5   },
    {7, 3   },
    {7, 4   },
    {7, 5   },
    {8, 3   },
    {8, 4   },
    {8, 5   },
    {8, 6   },
    {8, 7   },
    {8, 8   },
    {8, 9   },
    {8, 10  },
    {8, 11  },
    {8, 12  },
    {8, 13  },
    {8, 14  },
    {8, 15  },
    {8, 16  },
    {8, 17  },
    {8, 18  },
    {8, 19  },
    {8, 20  },
    {8, 21  },
    {8, 22  },
    {8, 23  },
    {8, 24  },
    {8, 24  },
    {8, 24  },
};

uint8_t g_tx_dig_gain[51][4] =
{
    //DIG_Gain(0xE5)   DIG_Gain(0xE6)    DIG_Gain(0xE7)     DIG_Gain(0xE8)
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x18, 0x0, 0x18},
    {0x0, 0x20, 0x0, 0x20},
    {0x0, 0x28, 0x0, 0x28},
};

