#ifndef  __REGISTER_H
#define  __REGISTER_H

#define RX_DC_CTRL_0        ( 0x04B )
#define RX_PWR_CTRL_0       ( 0x04C )
#define RX_DC_PWR_STATE_0   ( 0x04D )
#define RX1I_DC_OFST_1      ( 0x04E )
#define RX1I_DC_OFST_0      ( 0x04F )
#define RX1Q_DC_OFST_1      ( 0x050 )
#define RX1Q_DC_OFST_0      ( 0x051 )
#define RX2I_DC_OFST_1      ( 0x052 )
#define RX2I_DC_OFST_0      ( 0x053 )
#define RX2Q_DC_OFST_1      ( 0x054 )
#define RX2Q_DC_OFST_0      ( 0x055 )
#define RX1_AVG_PWR_2      	( 0x056 )
#define RX1_AVG_PWR_1       ( 0x057 )
#define RX1_AVG_PWR_0       ( 0x058 )
#define RX2_AVG_PWR_2       ( 0x059 )
#define RX2_AVG_PWR_1       ( 0x05A )
#define RX2_AVG_PWR_0       ( 0x05B )
#define RG_TX1_DAC_21      ( 0x7C2 )
#define RG_TX1_DAC_22      ( 0x7C3 )
#define RG_TX1_DAC_23      ( 0x7C4 )
#define RG_TX1_DAC_24      ( 0x7C5 )
#define RG_TX2_DAC_21      ( 0x7D2 )
#define RG_TX2_DAC_22      ( 0x7D3 )
#define RG_TX2_DAC_23      ( 0x7D4 )
#define RG_TX2_DAC_24      ( 0x7D5 )
#define REG_RX2_QEC_CTRL_0   ( 0xA00 )
#define REG_RX2_QEC_CTRL_1   ( 0xA01 )
#define REG_RX2_GOER_LEN     ( 0xA0C )
#define REG_RX2_GOER_ACC     ( 0xA0D )
#define REG_RX2_GOER_DONE    ( 0xA38 )
#define REG_RX2_GOER_FRQ0I_0 ( 0xA10 )
#define REG_RX2_GOER_FRQ0I_1 ( 0xA11 )
#define REG_RX2_GOER_FRQ0I_2 ( 0xA12 )
#define REG_RX2_GOER_FRQ0I_3 ( 0xA13 )
#define REG_RX2_GOER_FRQ0Q_0 ( 0xA14 )
#define REG_RX2_GOER_FRQ0Q_1 ( 0xA15 )
#define REG_RX2_GOER_FRQ0Q_2 ( 0xA16 )
#define REG_RX2_GOER_FRQ0Q_3 ( 0xA17 )
#define REG_RX2_GOER_FRQ1I_0 ( 0xA18 )
#define REG_RX2_GOER_FRQ1I_1 ( 0xA19 )
#define REG_RX2_GOER_FRQ1I_2 ( 0xA1A )
#define REG_RX2_GOER_FRQ1I_3 ( 0xA1B )
#define REG_RX2_GOER_FRQ1Q_0 ( 0xA1C )
#define REG_RX2_GOER_FRQ1Q_1 ( 0xA1D )
#define REG_RX2_GOER_FRQ1Q_2 ( 0xA1E )
#define REG_RX2_GOER_FRQ1Q_3 ( 0xA1F )

#define REG_RX2_GOER_PRT0I_0 ( 0xA28 )
#define REG_RX2_GOER_PRT0I_1 ( 0xA29 )
#define REG_RX2_GOER_PRT0I_2 ( 0xA2A )
#define REG_RX2_GOER_PRT0I_3 ( 0xA2B )
#define REG_RX2_GOER_PRT0I_4 ( 0xA04 )
#define REG_RX2_GOER_PRT0Q_0 ( 0xA2C )
#define REG_RX2_GOER_PRT0Q_1 ( 0xA2D )
#define REG_RX2_GOER_PRT0Q_2 ( 0xA2E )
#define REG_RX2_GOER_PRT0Q_3 ( 0xA2F )
#define REG_RX2_GOER_PRT0Q_4 ( 0xA05 )
#define REG_RX2_GOER_PRT1I_0 ( 0xA30 )
#define REG_RX2_GOER_PRT1I_1 ( 0xA31 )
#define REG_RX2_GOER_PRT1I_2 ( 0xA32 )
#define REG_RX2_GOER_PRT1I_3 ( 0xA33 )
#define REG_RX2_GOER_PRT1I_4 ( 0xA06 )
#define REG_RX2_GOER_PRT1Q_0 ( 0xA34 )
#define REG_RX2_GOER_PRT1Q_1 ( 0xA35 )
#define REG_RX2_GOER_PRT1Q_2 ( 0xA36 )
#define REG_RX2_GOER_PRT1Q_3 ( 0xA37 )
#define REG_RX2_GOER_PRT1Q_4 ( 0xA07 )
#define REG_RX2_GOER_RPT0_PWR ( 0xA39 )
#define REG_RX2_GOER_RPT1_PWR ( 0xA3A )

#define CRM_CLK_ICG_0 				      (0x0dd)

#define RG_RX1ADC_2 				      (0x698)
#define RG_RX1ADC_3 				      (0x699)
#define RG_RX1ADC_4 				      (0x69a)
#define RG_RX1ADC_5 				      (0x69b)
#define RG_RX1ADC_6 				      (0x69c)
#define RG_RX1ADC_7 				      (0x69d)
#define RG_RX1ADC_8 				      (0x69e)
#define RG_RX1ADC_9 				      (0x69f)
#define RG_RX1ADC_10 				      (0x6a0)
#define RG_RX1ADC_22                                  (0x6ac) 
#define RG_RX1ADC_23                                  (0x6ad) 
#define RG_RX1ADC_24                                  (0x6ae) 
#define RG_RX1ADC_25                                  (0x6af) 

#define RG_RX2ADC_2 				      (0x6b6)
#define RG_RX2ADC_3 				      (0x6b7)
#define RG_RX2ADC_4 				      (0x6b8)
#define RG_RX2ADC_5 				      (0x6b9)
#define RG_RX2ADC_6 				      (0x6ba)
#define RG_RX2ADC_7 				      (0x6bb)
#define RG_RX2ADC_8 				      (0x6bc)
#define RG_RX2ADC_9 				      (0x6bd)
#define RG_RX2ADC_10 				      (0x6be)
#define RG_RX2ADC_22                                  (0x6ca) 
#define RG_RX2ADC_23                                  (0x6cb) 
#define RG_RX2ADC_24                                  (0x6cc) 
#define RG_RX2ADC_25                                  (0x6cd) 

#define DA_RX2ADC_0 				      (0x6b4)
#define DA_RX2ADC_1 				      (0x6b5)
#define DA_RX2ADC_2 				      (0x6b6)

#define RG_LDO_3 			      	      (0x803)
#define RG_LDO_5 			      	      (0x805)
#define RG_TEST_19 				      (0x83b)


#define SETTING_DLY_CFG_RX1_0                         (0xE00)
#define SETTING_DLY_CFG_RX1_1                         (0xE01)
#define SETTING_DLY_CFG_RX1_2                         (0xE02)
#define SPLIT_GAIN_TABLE_CFG_RX1_0                    (0xE03)
#define SPLIT_GAIN_TABLE_CFG_RX1_1                    (0xE04)
#define SPLIT_GAIN_TABLE_CFG_RX1_2                    (0xE05)
#define SPLIT_GAIN_TABLE_CFG_RX1_3                    (0xE06)
#define FULL_GAIN_TABLE_CFG_RX1_0                     (0xE07)
#define FULL_GAIN_TABLE_CFG_RX1_1                     (0xE08)
#define FULL_GAIN_TABLE_CFG_RX1_2                     (0xE09)
#define FULL_GAIN_TABLE_CFG_RX1_3                     (0xE0A)
#define MAX_GAIN_CFG_RX1_0                            (0xE0B)
#define MAX_GAIN_CFG_RX1_1                            (0xE0C)
#define DETECTOR_CTRL_RX1_0                           (0xE0D)
#define DETECTOR_CTRL_RX1_1                           (0xE0E)
#define LMT_PDT_CFG_RX1_0                             (0xE0F)
#define LMT_PDT_CFG_RX1_1                             (0xE10)
#define LMT_PDT_CFG_RX1_2                             (0xE11)
#define LMT_PDT_CFG_RX1_3                             (0xE12)
#define LMT_PDT_CFG_RX1_4                             (0xE13)
#define LMT_PDT_CFG_RX1_5                             (0xE14)
#define LMT_PDT_CFG_RX1_6                             (0xE15)
#define LMT_PDT_CFG_RX1_7                             (0xE16)
#define LMT_PDT_CFG_RX1_8                             (0xE17)
#define LMT_PDT_CFG_RX1_9                             (0xE18)
#define ADC_PDT_CFG_RX1_0                             (0xE19)
#define ADC_PDT_CFG_RX1_1                             (0xE1A)
#define ADC_PDT_CFG_RX1_2                             (0xE1B)
#define ADC_PDT_CFG_RX1_3                             (0xE1C)
#define ADC_PDT_CFG_RX1_4                             (0xE1D)
#define ADC_PDT_CFG_RX1_5                             (0xE1E)
#define ADC_PDT_CFG_RX1_6                             (0xE1F)
#define ADC_PDT_CFG_RX1_7                             (0xE20)
#define ADC_PDT_CFG_RX1_8                             (0xE21)
#define HBF_AVP_CFG_RX1_1                             (0xE22)
#define HBF_AVP_CFG_RX1_2                             (0xE23)
#define HBF_AVP_CFG_RX1_3                             (0xE24)
#define HBF_AVP_CFG_RX1_4                             (0xE25)
#define HBF_AVP_CFG_RX1_5                             (0xE26)
#define GCTRL_INIT_CFG_RX1_0                          (0xE27)
#define GCTRL_INIT_CFG_RX1_1                          (0xE28)
#define GCTRL_INIT_CFG_RX1_2                          (0xE29)
#define GCTRL_INIT_CFG_RX1_3                          (0xE2A)
#define AGC_SLOW_ATTACK_CFG_RX1_0                     (0xE2B)
#define AGC_SLOW_ATTACK_CFG_RX1_1                     (0xE2C)
#define AGC_SLOW_ATTACK_CFG_RX1_2                     (0xE2D)
#define AGC_SLOW_ATTACK_CFG_RX1_3                     (0xE2E)
#define AGC_SLOW_ATTACK_CFG_RX1_4                     (0xE2F)
#define AGC_SLOW_ATTACK_CFG_RX1_5                     (0xE30)
#define AGC_SLOW_ATTACK_CFG_RX1_6                     (0xE31)
#define AGC_SLOW_ATTACK_CFG_RX1_7                     (0xE32)
#define AGC_SLOW_ATTACK_CFG_RX1_8                     (0xE33)
#define AGC_SLOW_ATTACK_CFG_RX1_9                     (0xE34)
#define AGC_SLOW_ATTACK_CFG_RX1_10                    (0xE35)
#define AGC_SLOW_ATTACK_CFG_RX1_11                    (0xE36)
#define AGC_SLOW_ATTACK_CFG_RX1_12                    (0xE37)
#define AGC_SLOW_ATTACK_CFG_RX1_13                    (0xE38)
#define AGC_SLOW_ATTACK_CFG_RX1_14                    (0xE39)
#define AGC_SLOW_ATTACK_CFG_RX1_15                    (0xE3A)
#define AGC_FAST_ATTACK_CFG_RX1_0                     (0xE3B)
#define AGC_FAST_ATTACK_CFG_RX1_1                     (0xE3C)
#define AGC_FAST_ATTACK_CFG_RX1_2                     (0xE3D)
#define AGC_FAST_ATTACK_CFG_RX1_3                     (0xE3E)
#define AGC_FAST_ATTACK_CFG_RX1_4                     (0xE3F)
#define AGC_FAST_ATTACK_CFG_RX1_5                     (0xE40)
#define AGC_FAST_ATTACK_CFG_RX1_6                     (0xE41)
#define AGC_FAST_ATTACK_CFG_RX1_7                     (0xE42)
#define AGC_FAST_ATTACK_CFG_RX1_8                     (0xE43)
#define AGC_FAST_ATTACK_CFG_RX1_9                     (0xE44)
#define AGC_FAST_ATTACK_CFG_RX1_10                    (0xE45)
#define AGC_FAST_ATTACK_CFG_RX1_11                    (0xE46)
#define AGC_FAST_ATTACK_CFG_RX1_12                    (0xE47)
#define AGC_FAST_ATTACK_CFG_RX1_13                    (0xE48)
#define AGC_FAST_ATTACK_CFG_RX1_14                    (0xE49)
#define AGC_FAST_ATTACK_CFG_RX1_15                    (0xE4A)
#define AGC_FAST_ATTACK_CFG_RX1_16                    (0xE4B)
#define AGC_FAST_ATTACK_CFG_RX1_17                    (0xE4C)
#define AGC_FAST_ATTACK_CFG_RX1_18                    (0xE4D)
#define AGC_FAST_ATTACK_CFG_RX1_19                    (0xE4E)
#define AGC_FAST_ATTACK_CFG_RX1_20                    (0xE4F)
#define AGC_FAST_ATTACK_CFG_RX1_21                    (0xE50)
#define AGC_FAST_ATTACK_CFG_RX1_22                    (0xE51)
#define AGC_FAST_ATTACK_CFG_RX1_23                    (0xE52)
#define MGC_CFG_RX1_0                                 (0xE53)
#define MGC_CFG_RX1_1                                 (0xE54)
#define MGC_CFG_RX1_2                                 (0xE55)
#define MGC_CFG_RX1_3                                 (0xE56)
#define MGC_CFG_RX1_4                                 (0xE57)
#define MGC_CFG_RX1_5                                 (0xE58)
#define GCTRL_RPT_RX1_0                               (0xE63)
#define GCTRL_RPT_RX1_1                               (0xE64)
#define GCTRL_RPT_RX1_2                               (0xE65)
#define GCTRL_RPT_RX1_3                               (0xE66)
#define GCTRL_RPT_RX1_4                               (0xE67)
#define GCTRL_RPT_RX1_5                               (0xE68)
#define GCTRL_RPT_RX1_6                               (0xE69)
#define GCTRL_RPT_RX1_7                               (0xE6A)
#define GCTRL_RPT_RX1_8                               (0xE6B)
#define GCTRL_RPT_RX1_9                               (0xE6C)
#define GCTRL_RPT_RX1_10                              (0xE6D)
#define GCTRL_RPT_RX1_11                              (0xE6E)
#define GCTRL_RPT_RX1_12                              (0xE6F)
#define GCTRL_RPT_RX1_13                              (0xE70)
#define GCTRL_RPT_RX1_14                              (0xE71)

#define SETTING_DLY_CFG_RX2_0                         (0xE80)
#define SETTING_DLY_CFG_RX2_1                         (0xE81)
#define SETTING_DLY_CFG_RX2_2                         (0xE82)
#define SPLIT_GAIN_TABLE_CFG_RX2_0                    (0xE83)
#define SPLIT_GAIN_TABLE_CFG_RX2_1                    (0xE84)
#define SPLIT_GAIN_TABLE_CFG_RX2_2                    (0xE85)
#define SPLIT_GAIN_TABLE_CFG_RX2_3                    (0xE86)
#define FULL_GAIN_TABLE_CFG_RX2_0                     (0xE87)
#define FULL_GAIN_TABLE_CFG_RX2_1                     (0xE88)
#define FULL_GAIN_TABLE_CFG_RX2_2                     (0xE89)
#define FULL_GAIN_TABLE_CFG_RX2_3                     (0xE8A)
#define MAX_GAIN_CFG_RX2_0                            (0xE8B)
#define MAX_GAIN_CFG_RX2_1                            (0xE8C)
#define DETECTOR_CTRL_RX2_0                           (0xE8D)
#define DETECTOR_CTRL_RX2_1                           (0xE8E)
#define LMT_PDT_CFG_RX2_0                             (0xE8F)
#define LMT_PDT_CFG_RX2_1                             (0xE90)
#define LMT_PDT_CFG_RX2_2                             (0xE91)
#define LMT_PDT_CFG_RX2_3                             (0xE92)
#define LMT_PDT_CFG_RX2_4                             (0xE93)
#define LMT_PDT_CFG_RX2_5                             (0xE94)
#define LMT_PDT_CFG_RX2_6                             (0xE95)
#define LMT_PDT_CFG_RX2_7                             (0xE96)
#define LMT_PDT_CFG_RX2_8                             (0xE97)
#define LMT_PDT_CFG_RX2_9                             (0xE98)
#define ADC_PDT_CFG_RX2_0                             (0xE99)
#define ADC_PDT_CFG_RX2_1                             (0xE9A)
#define ADC_PDT_CFG_RX2_2                             (0xE9B)
#define ADC_PDT_CFG_RX2_3                             (0xE9C)
#define ADC_PDT_CFG_RX2_4                             (0xE9D)
#define ADC_PDT_CFG_RX2_5                             (0xE9E)
#define ADC_PDT_CFG_RX2_6                             (0xE9F)
#define ADC_PDT_CFG_RX2_7                             (0xEA0)
#define ADC_PDT_CFG_RX2_8                             (0xEA1)
#define HBF_AVP_CFG_RX2_1                             (0xEA2)
#define HBF_AVP_CFG_RX2_2                             (0xEA3)
#define HBF_AVP_CFG_RX2_3                             (0xEA4)
#define HBF_AVP_CFG_RX2_4                             (0xEA5)
#define HBF_AVP_CFG_RX2_5                             (0xEA6)
#define GCTRL_INIT_CFG_RX2_0                          (0xEA7)
#define GCTRL_INIT_CFG_RX2_1                          (0xEA8)
#define GCTRL_INIT_CFG_RX2_2                          (0xEA9)
#define GCTRL_INIT_CFG_RX2_3                          (0xEAA)
#define AGC_SLOW_ATTACK_CFG_RX2_0                     (0xEAB)
#define AGC_SLOW_ATTACK_CFG_RX2_1                     (0xEAC)
#define AGC_SLOW_ATTACK_CFG_RX2_2                     (0xEAD)
#define AGC_SLOW_ATTACK_CFG_RX2_3                     (0xEAE)
#define AGC_SLOW_ATTACK_CFG_RX2_4                     (0xEAF)
#define AGC_SLOW_ATTACK_CFG_RX2_5                     (0xEB0)
#define AGC_SLOW_ATTACK_CFG_RX2_6                     (0xEB1)
#define AGC_SLOW_ATTACK_CFG_RX2_7                     (0xEB2)
#define AGC_SLOW_ATTACK_CFG_RX2_8                     (0xEB3)
#define AGC_SLOW_ATTACK_CFG_RX2_9                     (0xEB4)
#define AGC_SLOW_ATTACK_CFG_RX2_10                    (0xEB5)
#define AGC_SLOW_ATTACK_CFG_RX2_11                    (0xEB6)
#define AGC_SLOW_ATTACK_CFG_RX2_12                    (0xEB7)
#define AGC_SLOW_ATTACK_CFG_RX2_13                    (0xEB8)
#define AGC_SLOW_ATTACK_CFG_RX2_14                    (0xEB9)
#define AGC_SLOW_ATTACK_CFG_RX2_15                    (0xEBA)
#define AGC_FAST_ATTACK_CFG_RX2_0                     (0xEBB)
#define AGC_FAST_ATTACK_CFG_RX2_1                     (0xEBC)
#define AGC_FAST_ATTACK_CFG_RX2_2                     (0xEBD)
#define AGC_FAST_ATTACK_CFG_RX2_3                     (0xEBE)
#define AGC_FAST_ATTACK_CFG_RX2_4                     (0xEBF)
#define AGC_FAST_ATTACK_CFG_RX2_5                     (0xEC0)
#define AGC_FAST_ATTACK_CFG_RX2_6                     (0xEC1)
#define AGC_FAST_ATTACK_CFG_RX2_7                     (0xEC2)
#define AGC_FAST_ATTACK_CFG_RX2_8                     (0xEC3)
#define AGC_FAST_ATTACK_CFG_RX2_9                     (0xEC4)
#define AGC_FAST_ATTACK_CFG_RX2_10                    (0xEC5)
#define AGC_FAST_ATTACK_CFG_RX2_11                    (0xEC6)
#define AGC_FAST_ATTACK_CFG_RX2_12                    (0xEC7)
#define AGC_FAST_ATTACK_CFG_RX2_13                    (0xEC8)
#define AGC_FAST_ATTACK_CFG_RX2_14                    (0xEC9)
#define AGC_FAST_ATTACK_CFG_RX2_15                    (0xECA)
#define AGC_FAST_ATTACK_CFG_RX2_16                    (0xECB)
#define AGC_FAST_ATTACK_CFG_RX2_17                    (0xECC)
#define AGC_FAST_ATTACK_CFG_RX2_18                    (0xECD)
#define AGC_FAST_ATTACK_CFG_RX2_19                    (0xECE)
#define AGC_FAST_ATTACK_CFG_RX2_20                    (0xECF)
#define AGC_FAST_ATTACK_CFG_RX2_21                    (0xED0)
#define AGC_FAST_ATTACK_CFG_RX2_22                    (0xED1)
#define AGC_FAST_ATTACK_CFG_RX2_23                    (0xED2)
#define MGC_CFG_RX2_0                                 (0xED3)
#define MGC_CFG_RX2_1                                 (0xED4)
#define MGC_CFG_RX2_2                                 (0xED5)
#define MGC_CFG_RX2_3                                 (0xED6)
#define MGC_CFG_RX2_4                                 (0xED7)
#define MGC_CFG_RX2_5                                 (0xED8)
#define GCTRL_RPT_RX2_0                               (0xEE3)
#define GCTRL_RPT_RX2_1                               (0xEE4)
#define GCTRL_RPT_RX2_2                               (0xEE5)
#define GCTRL_RPT_RX2_3                               (0xEE6)
#define GCTRL_RPT_RX2_4                               (0xEE7)
#define GCTRL_RPT_RX2_5                               (0xEE8)
#define GCTRL_RPT_RX2_6                               (0xEE9)
#define GCTRL_RPT_RX2_7                               (0xEEA)
#define GCTRL_RPT_RX2_8                               (0xEEB)
#define GCTRL_RPT_RX2_9                               (0xEEC)
#define GCTRL_RPT_RX2_10                              (0xEED)
#define GCTRL_RPT_RX2_11                              (0xEEE)
#define GCTRL_RPT_RX2_12                              (0xEEF)
#define GCTRL_RPT_RX2_13                              (0xEF0)
#define GCTRL_RPT_RX2_14                              (0xEF1)


#define RG_REGS_46 				      (0xD2E)
#define RG_REGS_54 				      (0xD36)
#define RG_REGS_55 				      (0xD37)


#endif

